# Part 1: Data Analysis using NumPy
## 1. Why NumPy?
NumPy is written in C and stores data in contiguous memory blocks. This makes operations up to 50x faster than standard Python lists. It is the backbone of Pandas, Scikit-Learn, and TensorFlow.

In [46]:
import numpy as np
import time

# Quick speed comparison
py_list = list(range(1000000))
np_arr = np.arange(1000000)

start = time.time()
[x * 2 for x in py_list]
print(f"Python List Time: {time.time() - start:.4f} seconds")

start = time.time()
np_arr * 2
print(f"NumPy Array Time: {time.time() - start:.4f} seconds")

Python List Time: 0.0536 seconds
NumPy Array Time: 0.0031 seconds

## 2. Creating Arrays
Generating data structures from scratch or converting existing lists.

In [47]:
# 1D Array
arr_1d = np.array([10, 20, 30, 40])

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in Generators
zeros = np.zeros((3, 3))         # 3x3 matrix of 0.0
ones = np.ones((2, 4))           # 2x4 matrix of 1.0
evens = np.arange(0, 20, 2)      # Start 0, stop 20, step 2
dist = np.linspace(0, 100, 5)    # 5 evenly spaced numbers from 0 to 100
random_matrix = np.random.rand(3, 3) # 3x3 matrix of random floats 0-1

print("Evens Array:", evens)

Evens Array: [ 0  2  4  6  8 10 12 14 16 18]

## 3. Indexing & Slicing
Extracting specific elements or subsets of an array.

In [48]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Index 2:", arr[2])         # 30
print("Last element:", arr[-1])   # 60
print("Slice [1:4]:", arr[1:4])   # [20, 30, 40]
print("Slice [::2]:", arr[::2])   # Step by 2: [10, 30, 50]

# Conditional Indexing (Boolean Masking)
print("Greater than 30:", arr[arr > 30]) # [40, 50, 60]

Index 2: 30
Last element: 60
Slice [1:4]: [20 30 40]
Slice [::2]: [10 30 50]
Greater than 30: [40 50 60]

## 4. Multidimensional Indexing and Axis
In a 2D matrix, `axis=0` operates vertically (down rows), and `axis=1` operates horizontally (across columns).

In [49]:
matrix = np.array([
    [10, 20, 30], 
    [40, 50, 60], 
    [70, 80, 90]
])

print("Row 1, Col 2:", matrix[1, 2]) # 60
print("Get entire Row 0:", matrix[0, :]) # [10, 20, 30]
print("Get entire Col 1:", matrix[:, 1]) # [20, 50, 80]

# Axis Operations
print("Sum down columns (axis=0):", matrix.sum(axis=0)) # [120, 150, 180]
print("Sum across rows (axis=1):", matrix.sum(axis=1))  # [60, 150, 240]

Row 1, Col 2: 60
Get entire Row 0: [10 20 30]
Get entire Col 1: [20 50 80]
Sum down columns (axis=0): [120 150 180]
Sum across rows (axis=1): [ 60 150 240]

## 5. Data Types in NumPy
Forcing data types optimizes memory, crucial for large datasets.

In [50]:
# Default types
arr_float = np.array([1.5, 2.5, 3.5])
print("Original Type:", arr_float.dtype) # float64

# Convert (cast) to integer
arr_int = arr_float.astype(np.int32)
print("Cast to Int:", arr_int)           # [1, 2, 3]

Original Type: float64
Cast to Int: [1 2 3]

## 6. Broadcasting
Broadcasting lets NumPy do math on arrays of different shapes by "stretching" the smaller one.

In [51]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
row_vector = np.array([100, 200, 300])

print("Broadcast Scalar:\\n", matrix * scalar)
# [[10, 20, 30], [40, 50, 60]]

print("\\nBroadcast Vector:\\n", matrix + row_vector)
# [[101, 202, 303], [104, 205, 306]]

Broadcast Scalar:\n [[10 20 30]
 [40 50 60]]
\nBroadcast Vector:\n [[101 202 303]
 [104 205 306]]

## 7. Mathematical Functions

In [52]:
arr = np.array([1, 4, 9, 16, 25])

print("Square Root:", np.sqrt(arr))
print("Mean:", np.mean(arr))
print("Standard Dev:", np.std(arr))
print("Max value index (argmax):", np.argmax(arr)) # Returns index 4

Square Root: [1. 2. 3. 4. 5.]
Mean: 11.0
Standard Dev: 8.648699324175862
Max value index (argmax): 4

# Part 2: Data Analysis using Pandas
## 1. Getting Started, Core Data Structures & Creating DataFrames

In [53]:
import pandas as pd
import numpy as np

# 10 Complex Entities with mixed data types, missing values, and nested lists
complex_data = {
    'user_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'name': ['Kumar', 'Neha', 'Rahul', 'Zoya', 'Amit', 'Priya', 'Vikram', 'Sana', 'Rohit', 'Kavya'],
    'join_date': ['2023-01-15', '2022-11-01', '2024-02-20', '2021-07-10', '2023-09-05', 
                  '2020-12-12', '2024-01-08', '2023-06-25', '2022-03-14', '2024-03-01'],
    'department': ['Engineering', 'Data', 'Data', 'Design', 'Operations', 
                   'Engineering', 'Engineering', 'Marketing', 'Sales', 'Data'],
    'experience_level': ['Beginner', 'Advanced', 'Intermediate', None, 'Beginner', 
                         'Expert', 'Expert', 'Beginner', None, 'Advanced'],
    'connections': [15, 120, 45, np.nan, 12, 340, 410, 5, 210, 150],
    'is_active': [True, True, False, True, True, False, True, True, False, True],
    'skills': [
        ['Python'], 
        ['Python', 'SQL', 'AWS'], 
        ['Pandas', 'NumPy'], 
        ['Figma', 'UI/UX'], 
        ['Excel'], 
        ['Python', 'Machine Learning', 'Docker'], 
        ['C++', 'System Design'], 
        ['SEO', 'Copywriting'], 
        ['B2B Sales'], 
        ['SQL', 'Tableau', 'PowerBI']
    ]
}

df_complex = pd.DataFrame(complex_data)

# Convert the string dates into actual Pandas Datetime objects
df_complex['join_date'] = pd.to_datetime(df_complex['join_date'])

display(df_complex)

,user_id,name,join_date,department,experience_level,connections,is_active,skills
0,101,Kumar,2023-01-15,Engineering,Beginner,15.0,True,[Python]
1,102,Neha,2022-11-01,Data,Advanced,120.0,True,"[Python, SQL, AWS]"
2,103,Rahul,2024-02-20,Data,Intermediate,45.0,False,"[Pandas, NumPy]"
3,104,Zoya,2021-07-10,Design,None,NaN,True,"[Figma, UI/UX]"
4,105,Amit,2023-09-05,Operations,Beginner,12.0,True,[Excel]
5,106,Priya,2020-12-12,Engineering,Expert,340.0,False,"[Python, Machine Learning, Docker]"
6,107,Vikram,2024-01-08,Engineering,Expert,410.0,True,"[C++, System Design]"
7,108,Sana,2023-06-25,Marketing,Beginner,5.0,True,"[SEO, Copywriting]"
8,109,Rohit,2022-03-14,Sales,None,210.0,False,[B2B Sales]
9,110,Kavya,2024-03-01,Data,Advanced,150.0,True,"[SQL, Tableau, PowerBI]"

## 2. Selection & Filtering
Using `.loc` (label-based), `.iloc` (integer/position-based), and condition masks.

In [54]:
# 1. Select specific columns
names_and_conns = df_users[['name', 'connections']]

# 2. iloc: Select row 0 and 1, all columns
first_two = df_users.iloc[0:2, :]

# 3. Filtering: Multiple conditions (AND: &, OR: |)
advanced_users = df_users[(df_users['connections'] > 40) & (df_users['experience_level'] != 'Beginner')]

display(advanced_users)

    user_id    name experience_level  connections
1       102    Neha         Advanced          120
2       103   Rahul     Intermediate           45
3       104    Zoya             None           80
5       106   Priya     Intermediate           65
6       107  Vikram           Expert          340
8       109   Rohit             None          210
9       110   Kavya         Advanced          150
10      111   Arjun     Intermediate           55
12      113  Manish           Expert          410
13      114   Sneha     Intermediate           75
14      115   Rohan             None           90

## 3. Cleaning & Preprocessing
Handling `NaN` (Missing) values and fixing data types.

In [55]:
# Create a copy to keep original safe
df_clean = df_users.copy()

# Fill missing experience levels with the Mode (Most common)
mode_exp = df_clean['experience_level'].mode()[0]
df_clean['experience_level'] = df_clean['experience_level'].fillna(mode_exp)

# Drop duplicates (if any existed)
df_clean = df_clean.drop_duplicates()

display(df_clean)

    user_id    name experience_level  connections
0       101   Kumar         Beginner           15
1       102    Neha         Advanced          120
2       103   Rahul     Intermediate           45
3       104    Zoya         Beginner           80
4       105    Amit         Beginner           12
5       106   Priya     Intermediate           65
6       107  Vikram           Expert          340
7       108    Sana         Beginner            5
8       109   Rohit         Beginner          210
9       110   Kavya         Advanced          150
10      111   Arjun     Intermediate           55
11      112   Aisha         Beginner            8
12      113  Manish           Expert          410
13      114   Sneha     Intermediate           75
14      115   Rohan         Beginner           90

## 4. Transformation
Modifying existing columns or creating new ones based on logic.

In [56]:
# Using .map() to standardize string cases
df_clean['experience_level'] = df_clean['experience_level'].str.upper()

# Using .apply() with a lambda function for custom logic
df_clean['is_influencer'] = df_clean['connections'].apply(lambda x: True if x >= 100 else False)

display(df_clean)

    user_id    name experience_level  connections  is_influencer
0       101   Kumar         BEGINNER           15          False
1       102    Neha         ADVANCED          120           True
2       103   Rahul     INTERMEDIATE           45          False
3       104    Zoya         BEGINNER           80          False
4       105    Amit         BEGINNER           12          False
5       106   Priya     INTERMEDIATE           65          False
6       107  Vikram           EXPERT          340           True
7       108    Sana         BEGINNER            5          False
8       109   Rohit         BEGINNER          210           True
9       110   Kavya         ADVANCED          150           True
10      111   Arjun     INTERMEDIATE           55          False
11      112   Aisha         BEGINNER            8          False
12      113  Manish           EXPERT          410           True
13      114   Sneha     INTERMEDIATE           75          False
14      115   Rohan         BEGINNER           90          False

## 5. Melt & Pivot
Reshaping data. Pivot goes Long-to-Wide, Melt goes Wide-to-Long.

In [57]:
# Pivot Table Example: Average connections per experience level
pivot_df = df_clean.pivot_table(
    values='connections', 
    index='experience_level', 
    aggfunc='mean'
)
display(pivot_df)

# Melt Example: Unpivoting
melted_df = pd.melt(
    df_clean, 
    id_vars=['user_id', 'name'], 
    value_vars=['connections', 'is_influencer'],
    var_name='Metric', 
    value_name='Value'
)
display(melted_df.head(4))

                  connections
experience_level
ADVANCED                135.0
BEGINNER                 60.0
EXPERT                  375.0
INTERMEDIATE             60.0

   user_id   name       Metric Value
0      101  Kumar  connections    15
1      102   Neha  connections   120
2      103  Rahul  connections    45
3      104   Zoya  connections    80

## 6. Aggregation & Grouping
Summarizing data categories.

In [58]:
# Group by experience and calculate multiple aggregates
summary_stats = df_clean.groupby('experience_level').agg({
    'user_id': 'count',                 # Count users
    'connections': ['mean', 'max']      # Avg and Max connections
})

# Rename columns for clarity
summary_stats.columns = ['Total Users', 'Avg Connections', 'Max Connections']
display(summary_stats)

                  Total Users  Avg Connections  Max Connections
experience_level
ADVANCED                    2            135.0              150
BEGINNER                    7             60.0              210
EXPERT                      2            375.0              410
INTERMEDIATE                4             60.0               75

## 7. Merging & Joining
Combining datasets using SQL-like logic (Inner, Left, Right, Outer).

In [59]:
# Creating a second DataFrame representing network likes
likes_data = {
    'user_id': [101, 103, 105, 109],
    'total_likes': [350, 120, 45, 900]
}
df_likes = pd.DataFrame(likes_data)

# Left Join: Keep all users, attach likes if they exist
merged_df = pd.merge(df_clean, df_likes, on='user_id', how='left')

# Fill NaN likes with 0
merged_df['total_likes'] = merged_df['total_likes'].fillna(0)
display(merged_df)

    user_id    name experience_level  connections  is_influencer  total_likes
0       101   Kumar         BEGINNER           15          False        350.0
1       102    Neha         ADVANCED          120           True          0.0
2       103   Rahul     INTERMEDIATE           45          False        120.0
3       104    Zoya         BEGINNER           80          False          0.0
4       105    Amit         BEGINNER           12          False         45.0
5       106   Priya     INTERMEDIATE           65          False          0.0
6       107  Vikram           EXPERT          340           True          0.0
7       108    Sana         BEGINNER            5          False          0.0
8       109   Rohit         BEGINNER          210           True        900.0
9       110   Kavya         ADVANCED          150           True          0.0
10      111   Arjun     INTERMEDIATE           55          False          0.0
11      112   Aisha         BEGINNER            8          False          0.0
12      113  Manish           EXPERT          410           True          0.0
13      114   Sneha     INTERMEDIATE           75          False          0.0
14      115   Rohan         BEGINNER           90          False          0.0

## 8. Working with CSVs
Reading from and writing to files.

In [60]:
# Write the fully processed DataFrame to a CSV
merged_df.to_csv('processed_network_users.csv', index=False)
print("File saved as 'processed_network_users.csv'")

# Read it back into Pandas
df_reloaded = pd.read_csv('processed_network_users.csv')
display(df_reloaded.head(2))

File saved as 'processed_network_users.csv'

   user_id   name experience_level  connections  is_influencer  total_likes
0      101  Kumar         BEGINNER           15          False        350.0
1      102   Neha         ADVANCED          120           True          0.0